### ISSUE TITLE
keyinfo / openpgp fails on a ecc key

### ISSUE THREAD

**Issue by KAYLukas** [ProtonMail/pmcrypto#14]
It can't request the bitsize of a key.
cf:
```
TypeError: this.params[0].byteLength is not a function
    at i.getBitSize (openpgp.min.js:2)
    at vendor.js:80215
    at <anonymous>
```

**Comment by sanjanarajan** [comment]
Ah it's a bug in OpenPGP that doesn't check whether a parameter is an MPI before getting the bit size - I will fix it tomorrow at the latest
