### ISSUE TITLE
Replace or strip down MailParser code

### ISSUE THREAD

**Issue by larabr** [ProtonMail/pmcrypto#143]
It's a very large library with redundant/unclear dependencies.

**Comment by twiss** [comment]
For future reference, to me the most promising library seems [jsmime](https://github.com/mozilla-comm/jsmime), which is used by Thunderbird (newer version in-tree [here](https://github.com/mozilla/releases-comm-central/tree/master/mailnews/mime/jsmime)). The only missing feature seems to be UTF-7 support, which Thunderbird patched in [here](https://github.com/mozilla/releases-comm-central/blob/master/mailnews/mime/src/jsmime.jsm). We should probably do the same. We could also fork the first repo, update it, and add UTF-7 support there, that might be less hacky.
