### ISSUE TITLE
`binaryStringToArray` and `arrayToBinaryString` encoding

### ISSUE THREAD

**Issue by BafS** [ProtonMail/pmcrypto#19]
The encoding/decoding of binaryStringToArray/arrayToBinaryString is problematic for unicode chars. 

encoding | result
---------- | -------------
`pmc.binaryStringToArray('aéこん')` | `Uint8Array(4) [97, 233, 83, 147]`
`new TextEncoder('utf-8').encode('aéこん')` | `Uint8Array(9) [97, 195, 169, 227, 129, 147, 227, 130, 147]`

decoding | result
---------- | -------------
`pmc.arrayToBinaryString([97, 233, 83, 147])` | `aéS` (not the expected result; `aéこん`)

- [`str2ab('aéこん')`](https://developers.google.com/web/updates/2012/06/How-to-convert-ArrayBuffer-to-and-from-String) gives an ArrayBuffer of
  - `Int8Array(8) [97, 0, -23, 0, 83, 48, -109, 48]`
  - `Int16Array(4) [97, 233, 12371, 12435]`
  - `Int32Array(2) [15269985, 814952531]`
  - `Uint8Array(8) [97, 0, 233, 0, 83, 48, 147, 48]`

Ref:
 - https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder

**Comment by bartbutler** [comment]
It's not the right function for unicode characters. Use encode_utf8 followed by binaryStringToArray.

**Comment by BafS** [comment]
`pmcrypto.binaryStringToArray(pmcrypto.encode_utf8('aéこん'))`
> [97, 195, 169, 227, 129, 147, 227, 130, 147]

`pmcrypto.decode_utf8(pmcrypto.arrayToBinaryString(([97, 195, 169, 227, 129, 147, 227, 130, 147])))`
> 'aéこん'
