### ISSUE TITLE
Wrong comparison (boolean compared to number)?

### ISSUE THREAD

**Issue by vladimiry** [ProtonMail/pmcrypto#53]
Just wanted to highlight a potentially wrong comparison [here](https://github.com/ProtonMail/pmcrypto/blob/473569dee4ad9db5e491ece5b44d651915787a0e/lib/message/processMIME.js#L33):
```javascript
if (!parts.length === 4) {
```
There is a comparison of boolean with number.

**Comment by mmso** [comment]
Thanks for your report @vladimiry
