### ISSUE TITLE
When retrieving expiration time for public keys imported for contacts, use "encrypt" instead of "encrypt_sign"

### ISSUE THREAD

**Issue by sanjanarajan** [ProtonMail/pmcrypto#57]
https://github.com/ProtonMail/pmcrypto/blob/master/lib/key/info.js#L77

To determine the expiration time of a key we usually do this in the context of both encrypting and signing by passing in "encrypt_sign". For contact public keys, because we only use them for encryption, we can pass in just "encrypt" here instead.

**Comment by mmso** [comment]
We solved this in another way
