### ISSUE TITLE
Verifying encrypted streaming data with signature fails

### ISSUE THREAD

**Issue by vincaslt** [ProtonMail/pmcrypto#98]
```
const { data } = await decryptMessage({
    message: openpgp.message.read(stream),
    signature: getSignature(decryptedSignature),
    sessionKeys: keys.sessionKeys,
    publicKeys: keys.privateKey.toPublic(),
    streaming: 'web',
    format: 'binary',
});
```

Code like this will fail with `Cannot convert undefined or null to object` because of 
https://github.com/ProtonMail/pmcrypto/blob/706e95c71534b3889cdc46ee05eac4a92fb47fa6/lib/message/utils.js#L88-L90

This function is passed a Promise of signature (because of streaming decryption), so packets resolves to undefined.

This function should possibly accept and return a promise. There are three scenarios which I can think of in which it must work:
- streaming decryption + known signature (like original example)
- streaming decryption + inlined signature (promise is required in that case)
- non-streaming decryption + signature

**Comment by twiss** [comment]
Should be fixed by #101.
